chore: Allow for async taps of targets
magento/pwa-studio pull request #2718
Opened 2020-09-21 14:51 UTC by sirugh

## Description

It may come to be that we need to perform some async calls to determine available routes. This change makes that possible.

## Related Issue

Closes #ISSUE_NUMBER.

## Acceptance 

### Verification Stakeholders

### Specification

### Verification Steps

1. Go to the FOO page.
2. Verify the BAR shows up.
3. Make sure BAZ does a thing.

## Screenshots / Screen Captures (if appropriate)

## Checklist

- [ ] I have added tests to cover my changes, if necessary.
* I have updated the documentation accordingly, if necessary.

2020-09-21 15:42 UTC, zetlen requested changes
This oughta do it.

2020-09-21 15:42 UTC, zetlen commented on packages/pwa-buildpack/lib/WebpackTools/configureWebpack/configureWebpack.js
> +    bus.getTargetsOf('@magento/pwa-buildpack').transformModules.promise(x =>
```suggestion
    await bus.getTargetsOf('@magento/pwa-buildpack').transformModules.promise(x =>
```

2020-09-21 15:42 UTC, zetlen commented on packages/pwa-buildpack/lib/TestHelpers/testFullBuild.js
> +    bus.getTargetsOf('@magento/pwa-buildpack').transformModules.promise(x =>
```suggestion
    await bus.getTargetsOf('@magento/pwa-buildpack').transformModules.promise(x =>
```

2020-09-21 21:42 UTC, zetlen approved these changes
LGTM 👍 Thanks for boldly maintaining the targets framework. This change is backward-compatible!

2020-09-22 16:52 UTC, tjwiebell approved these changes
Made sense after your explanation and with some refresher of `webpack/tapable`. Would like to see an example of how position in the waterfall works, but that's probably easier to understand when a route makes use of this change (Wishlist maybe?).

2020-09-23 19:25 UTC, revanth0212 commented
QA Done 👍

2020-09-23 19:42 UTC, merged