Update index.md
magento/pwa-studio pull request #2761
Opened 2020-10-07 06:01 UTC by abrarpathan19

## Description

Added content for PWA benefits from user point of view. 

## Related Issue

Closes #ISSUE_NUMBER.

## Acceptance 

### Verification Stakeholders

### Specification

### Verification Steps

1. Go to the FOO page.
2. Verify the BAR shows up.
3. Make sure BAZ does a thing.

## Screenshots / Screen Captures (if appropriate)

## Checklist

- [ ] I have added tests to cover my changes, if necessary.
* I have updated the documentation accordingly, if necessary.

2020-10-12 17:44 UTC, jcalcaben requested changes

2020-10-12 17:44 UTC, jcalcaben commented on pwa-devdocs/src/technologies/overview/index.md
> +This strategy is known as the RAIL model:
would be useful to add a link to an external website for more information about this model

2020-11-16 19:01 UTC, sirugh requested changes
Please make the requested changes!

2020-11-16 19:01 UTC, sirugh commented on pwa-devdocs/src/technologies/overview/index.md
> +This strategy is known as the RAIL model:
```suggestion
This strategy is known as the [RAIL](https://web.dev/rail/) model:
```

2020-11-17 15:36 UTC, sirugh approved these changes
Thanks!

2020-11-17 15:37 UTC, jcalcaben approved these changes

2020-11-17 15:59 UTC, merged