Move product detail GraphQl fields to fragment
magento/pwa-studio pull request #2868
Opened 2020-11-19 15:03 UTC by huykon

## Description

Base on [#1027](https://github.com/magento/graphql-ce/issues/1027) Use ProductInterface fragment for product detail query.

## Acceptance

### Verification Stakeholders

### Specification

### Verification Steps

1. Go to the product detail page.
2. Verify the product data shows up.
3. Make sure everything working well.

## Screenshots / Screen Captures (if appropriate)

## Checklist

* I have added tests to cover my changes, if necessary.
* I have added translations for new strings, if necessary.
* I have updated the documentation accordingly, if necessary.

2020-11-19 16:27 UTC, sirugh requested changes
I checked the fragment use and it does seem like graphql-ce/1027 was resolved and the fragment returns the correct data. I would still want to do a regression on the PDP.

While you're here making changes to the GQL files, would you mind moving the Product RootComponent query and fragment to peregrine? You can import and use like the [`useBreadcrumbs` talon](https://github.com/magento/pwa-studio/blob/develop/packages/peregrine/lib/talons/Breadcrumbs/useBreadcrumbs.js#L37).

2020-11-19 16:27 UTC, sirugh commented on packages/venia-ui/lib/RootComponents/Product/product.gql.js
> -                __typename
I believe `__typename` got lost in the copy to the fragment. Can you add it back?

2020-11-19 16:27 UTC, sirugh commented on packages/venia-ui/lib/components/CartPage/ProductListing/EditModal/productForm.js
> +                ...ProductDetailsFragment
Unfortunately you cannot just re-use the fragment here and the content needed by the `RootComponent/Product` and the content needed by this component are different. Re-using the fragment will result in over-fetching of data. 

Please revert this change, or create a `productFormFragment`.

2020-11-19 16:27 UTC, sirugh commented on packages/venia-ui/lib/components/LegacyMiniCart/editItem.js
> +                ...ProductDetailsFragment
Same comment here. Unfortunately you cannot just re-use the fragment here and the content needed by the `RootComponent/Product` and the content needed by this component are different. Re-using the fragment will result in over-fetching of data. 

Please revert this change, or create an `editFormFragment`.

2020-11-20 03:28 UTC, sirugh approved these changes
I think I see why you didn't move the other fragments to talons as those components define their gql in the same file. I think that is fine for now, so please don't feel like it's necessary to do any further.

Thanks for this!

2020-11-20 03:32 UTC, huykon commented
Thank you! I hope this done :)

2020-11-30 22:25 UTC, dpatil-magento commented
QA Approved.

2020-11-30 22:26 UTC, merged