Handle array of paths as route pattern
magento/pwa-studio pull request #2893
Opened 2020-12-04 11:16 UTC by papiliond

## Description

TODO: Extend the functionality of the Routes target of venia-ui. Handle both `string` and `string[]` type of the react-router path prop (see [docs](https://reactrouter.com/web/api/Route/path-string-string)).

## Related Issue
Closes #2892

## Acceptance

### Verification Stakeholders

### Specification

### Verification Steps

1. Add/modify an entry in "packages/venia-ui/lib/defaultRoutes.json" and define the `pattern` with an array value. For example:
```
    {
        "name": "AccountInformationPage",
        "pattern": ["/account-information", "/acc-info"],
        "exact": true,
        "path": "../AccountInformationPage"
    }
```
2. Run the project with `yarn watch`
3. Navigating to "/account-information" and "/acc-info" gives you the same page

## Screenshots / Screen Captures (if appropriate)

## Checklist

* I have added tests to cover my changes, if necessary.
* I have added translations for new strings, if necessary.
* I have updated the documentation accordingly, if necessary.

2020-12-04 14:48 UTC, sirugh requested changes
Would you mind adding tests for the cases we are supporting here? Two simple assertions for the expected string in both cases would suffice. You'll also want to make sure to check on the failing test.

Also please make sure to run `yarn prettier` and potentially `yarn lint` to fix any lint errors.

2020-12-04 14:48 UTC, sirugh commented on packages/venia-ui/lib/targets/makeRoutesTarget.js
>              }"><${AddedRoute}/></Route>`
The `routePath` creation now adds the double-quotes or brackets when necessary so you should remove them from line 20/22.

2020-12-04 14:48 UTC, sirugh commented on packages/venia-ui/lib/targets/makeRoutesTarget.js
> +        `{[${route.pattern.map(path => `"${path}"`).join(", ")}]}` : `"${route.pattern}"`;
`JSON.stringify` works as well and is a bit easier to read.

```suggestion
        `{[${JSON.stringify(route.pattern}]}` : `"${route.pattern}"`;
```

2020-12-04 15:37 UTC, papiliond commented
@sirugh Thanks for answering. Will create tests and review your suggestions this weekend.

2020-12-06 08:03 UTC, papiliond commented
@sirugh Made some refactors and added tests for the two cases.

2020-12-07 16:02 UTC, sirugh approved these changes

2020-12-07 18:11 UTC, dpatil-magento commented
QA Approved.

2020-12-07 18:11 UTC, merged