Update index.md
magento/pwa-studio pull request #2917
Opened 2020-12-22 06:13 UTC by RakeshJesadiya

Fixed multiple broken anchor links and update some of the files name that were changed.

## Description

page with multiple outdated content like broken anchor links, some of the files name were changed. Fixed anchor link with filename.

## Affected Page

https://magento.github.io/pwa-studio/venia-pwa-concept/project-structure/

2020-12-22 22:14 UTC, revanth0212 requested changes
Thank you, @RakeshJesadiya for the PR. I have made a small comment about the SW file. Please check.

2020-12-22 22:14 UTC, revanth0212 commented on pwa-devdocs/src/venia-pwa-concept/project-structure/index.md
> +### [`src/registerSW.js`][]
I don't think this is accurate. `registerSw.js` contains logic to register a SW on the app. `sw.js` contains the main Service Worker logic. `sw.js` is the first file from where the webpack bundling of the SW starts.

2021-01-19 17:27 UTC, sirugh commented
@magento create issue from PR

2021-02-09 16:12 UTC, sirugh commented
Closing for lack of movement.

2021-02-09 16:12 UTC, closed without merging