Remove lodash from create-pwa
magento/pwa-studio pull request #3003
Opened 2021-02-09 20:44 UTC by jimbo

## Description

Remove `lodash` from `@magento/create-pwa`.

## Related Issue

PWA-1452

## Acceptance

### Verification Stakeholders

- @dpatil-magento 
- @revanth0212 

### Specification

### Verification Steps

1. `yarn create` should work

## Screenshots / Screen Captures (if appropriate)

## Checklist

* I have added tests to cover my changes, if necessary.
* I have added translations for new strings, if necessary.
* I have updated the documentation accordingly, if necessary.

2021-02-09 21:04 UTC, revanth0212 approved these changes

2021-02-09 21:05 UTC, revanth0212 requested changes
Samplebackends are showing up as `undefined`.

![image](https://user-images.githubusercontent.com/35203638/107428495-540c9600-6ae8-11eb-93c7-e5c06e497488.png)

2021-02-09 21:30 UTC, supernova-at approved these changes

2021-02-09 22:04 UTC, jimbo reviewed
@revanth0212 LGTM

2021-02-09 22:07 UTC, dpatil-magento approved these changes

2021-02-10 18:01 UTC, sirugh commented on packages/pwa-buildpack/lib/cli/create-project.js
> -module.exports.sampleBackends = require('../../sampleBackends.json');
Not sure you should delete this just yet - it's still used here: https://github.com/magento/pwa-studio/blob/develop/packages/pwa-buildpack/lib/cli/generate-build-report.js#L12

2021-02-10 18:19 UTC, sirugh approved these changes
this should work - now we just need to test it.

2021-02-10 18:20 UTC, revanth0212 approved these changes
Working when used against `node packages/create-pwa/bin/create-pwa`. Need to publish check against `yarn create @magento/pwa`. Thanks for working on this @jimbo.

2021-02-10 18:52 UTC, dpatil-magento commented
Ignore the coveralls build, it triggered because of push event. @jimbo Please check on test failure though.

2021-02-10 19:32 UTC, sirugh approved these changes

2021-02-10 20:58 UTC, revanth0212 approved these changes

2021-02-10 20:58 UTC, merged