Release notes 9.0.1
magento/pwa-studio pull request #3005
Opened 2021-02-09 22:16 UTC by jcalcaben

## Description

Creates the release notes for 9.0.1

## Related Issue

Closes #ISSUE_NUMBER.

## Acceptance

@davemacaulay 

### Verification Stakeholders

@davemacaulay 

### Specification

### Verification Steps

1. Open CHANGELOG.md
2. Verify content is accurate

## Screenshots / Screen Captures (if appropriate)

## Checklist

* I have added tests to cover my changes, if necessary.
* I have added translations for new strings, if necessary.
* I have updated the documentation accordingly, if necessary.

2021-02-09 22:19 UTC, davemacaulay approved these changes

2021-02-09 22:20 UTC, davemacaulay requested changes

2021-02-09 22:20 UTC, davemacaulay commented on CHANGELOG.md
> +-   [What's new in 9.0.1](#whats-new-in-900)
`#whats-new-in-901`?

2021-02-09 22:22 UTC, davemacaulay submitted a review, later dismissed

2021-02-11 15:23 UTC, dpatil-magento approved these changes

2021-02-11 15:23 UTC, merged