[doc] Release notes 10.0.0
magento/pwa-studio pull request #3067
Opened 2021-03-18 20:55 UTC by jcalcaben

## Description

Updates the CHANGELOG and compatibility table for 10.0.0
## Related Issue

Closes PWA-1565

## Acceptance

@davemacaulay
@ericerway 
@tkacheva 

### Verification Stakeholders

@davemacaulay
@ericerway 
@tkacheva 

### Specification

### Verification Steps

1. Open CHANGELOG
2. Verify content is accurate

## Screenshots / Screen Captures (if appropriate)

## Checklist

* I have added tests to cover my changes, if necessary.
* I have added translations for new strings, if necessary.
* I have updated the documentation accordingly, if necessary.

2021-03-24 15:55 UTC, jcalcaben commented
Updated image

![pwa-scaffold-template](https://user-images.githubusercontent.com/4692281/112341120-25f5a680-8c8f-11eb-9174-122dcc1eb5c4.png)

2021-03-29 16:43 UTC, dpatil-magento requested changes
Pls add https://github.com/magento/pwa-studio/pull/3065 merged on release branch.

2021-03-29 16:43 UTC, dpatil-magento commented on CHANGELOG.md
> +If the Magento backend has the **Check or Money Order** option enabled, this extension lets storefront customers use this payment option.
`Make check Payable to` and `Send Check to`  does not have GraphQL coverage, should this be noted in known issues or somewhere?  More info https://github.com/magento/pwa-studio/pull/2969#issuecomment-797654096

2021-03-29 16:43 UTC, dpatil-magento commented on CHANGELOG.md
GraphQL issue https://jira.corp.magento.com/browse/PWA-1298 is fixed on 2.4-develop, good to add this note/info info if customers like to get patch.

2021-03-29 18:14 UTC, dpatil-magento approved these changes

2021-03-29 18:21 UTC, davemacaulay submitted a review, later dismissed

2021-03-29 18:53 UTC, supernova-at approved these changes

2021-03-29 18:54 UTC, supernova-at commented on CHANGELOG.md
> +The build report tool is a Buildpack CLI command that returns information about their storefront setup and development environment.
```suggestion
The build report tool is a Buildpack CLI command that returns information about a storefront setup and development environment.
```

2021-03-29 19:12 UTC, dpatil-magento approved these changes

2021-03-29 19:36 UTC, ericerway submitted a review, later dismissed

2021-03-29 20:09 UTC, supernova-at approved these changes

2021-03-29 20:22 UTC, merged