Update devdoc dependencies
magento/pwa-studio pull request #3072
Opened 2021-03-19 16:38 UTC by jcalcaben

## Description

Update devdoc dependencies

## Related Issue

Closes #ISSUE_NUMBER.

## Acceptance

### Verification Stakeholders

### Specification

### Verification Steps

1. Navigate to the devdocs project
2. Run an audit: `yarn audit`
3. Verify 0 packages needed to update

## Screenshots / Screen Captures (if appropriate)

## Checklist

* I have added tests to cover my changes, if necessary.
* I have added translations for new strings, if necessary.
* I have updated the documentation accordingly, if necessary.

2021-03-19 19:10 UTC, sirugh requested changes
Nothing broke with the webpack/cli major updates?

2021-03-19 19:20 UTC, jcalcaben commented
@sirugh None that I've seen when I build or run the HTML preview server

2021-03-19 19:37 UTC, sirugh submitted a review, later dismissed

2021-03-29 18:10 UTC, dpatil-magento approved these changes

2021-03-29 18:11 UTC, merged