[BUGFIX] The browser back button wasn't responding
magento/pwa-studio pull request #3078
Opened 2021-03-22 09:29 UTC by Jordaneisenburger

## Description

Check for [#3077](https://github.com/magento/pwa-studio/issues/3077) for explanation.

## Related Issue

Closes #3077.

## Acceptance

### Verification Stakeholders

### Specification

### Verification Steps

Go to https://venia.magento.com/default/venia-tops/venia-blouses.html?page=1
Add some filters
Now click on the browser back button once
You should see we're back to the prev page/state

## Screenshots / Screen Captures (if appropriate)

## Checklist

* I have added tests to cover my changes, if necessary.
* I have added translations for new strings, if necessary.
* I have updated the documentation accordingly, if necessary.

2021-03-23 14:24 UTC, anthoula commented
@Jordaneisenburger Nice catch. The change looks good. Would you add some test coverage?

2021-03-23 14:25 UTC, anthoula requested changes
@Jordaneisenburger Nice catch. The change looks good. Would you add some test coverage?

2021-04-12 19:17 UTC, anthoula approved these changes

2021-04-13 20:13 UTC, dpatil-magento commented
QA Approved. 

@Jordaneisenburger @anthoula Created new bug for similar fix on search page https://github.com/magento/pwa-studio/issues/3118

2021-04-13 20:25 UTC, merged