Added possibility to allow trusted vendors to change code outside their namespace (#3156)
magento/pwa-studio pull request #3266
Opened 2021-07-13 10:22 UTC by 0m3r

add option TRUSTED_VENDORS into .env
and add custom checking into file: packages/pwa-buildpack/lib/WebpackTools/ModuleTransformConfig.js _assertAllowedToTransform

## Description

Added possibility to allow trusted vendors to change code outside their namespace

## Related Issue

Closes #3156.

## Acceptance

@sirugh
@zetlen

### Verification Stakeholders

@jerschipper
@Jordaneisenburger

#### Test scenario(s) for direct fix/feature

in your .env  add 

```
...
TRUSTED_VENDORS=@vendor
```
intercept.js
```js
const { Targetables } = require('@magento/pwa-buildpack');
module.exports = targets => {
   const targetables = Targetables.using(targets);

   const HeaderComponent = targetables.reactComponent(
        '@magento/venia-ui/lib/components/Header/header.js'
    );
    
    HeaderComponent.insertAfterJSX(    
        '<SearchBar isOpen={isSearchOpen} ref={searchRef} />',
        `<span>INSERTED</span>`
    );
}
```

2021-07-13 22:14 UTC, fooman commented
@0m3r I like the direction where this is going. I am a little bit afraid that having this part of the .env makes a bit harder than necessary to administer though. Ideally the decision to add a vendor as trusted is done on a per project basis rather than on a per environment basis. It could lead to hard to track down issues once you end up with a list longer than a few vendors.

Ideally this configuration could live in a file that is part of the checked in code for the project. packages.json might a good fit as part of this:

```
  "pwa-studio": {
    "targets": {
      "intercept": "./local-intercept.js"
    }
```

to

```
  "pwa-studio": {
    "targets": {
      "intercept": "./local-intercept.js"
    },
   "trusted_vendors":  [
      "@vendor"
   ]
```

2021-07-28 12:54 UTC, larsroettig commented
> @0m3r I like the direction where this is going. I am a little bit afraid that having this part of the .env makes a bit harder than necessary to administer though. Ideally the decision to add a vendor as trusted is done on a per project basis rather than on a per environment basis. It could lead to hard to track down issues once you end up with a list longer than a few vendors.
> 
> Ideally this configuration could live in a file that is part of the checked in code for the project. packages.json might a good fit as part of this:
> 
> ```
>   "pwa-studio": {
>     "targets": {
>       "intercept": "./local-intercept.js"
>     }
> ```
> 
> to
> 
> ```
>   "pwa-studio": {
>     "targets": {
>       "intercept": "./local-intercept.js"
>     },
>    "trusted_vendors":  [
>       "@vendor"
>    ]
> ```

Hi @0m3r. I totally agree with @fooman from my point of view this would be very nice if we can do this via `package.json`. 
Currently, I will ask the core team about their opinion. 


kind regards, 

Lars

2021-07-29 09:18 UTC, 0m3r commented
> Currently, I will ask the core team about their opinion.
what about core team opinion?

2021-07-29 09:26 UTC, larsroettig commented
@supernova-at agreed with me on this yesterday would be cool if you can do it

2021-07-29 13:59 UTC, 0m3r commented
@larsroettig review this commit https://github.com/magento/pwa-studio/pull/3266/commits/e29c51e11ac9167f1102a0d8b95ddac5e5816f94, please

2021-07-30 09:48 UTC, larsroettig requested changes
Hi @0m3r, 
The code looks good pls. Add **test coverage**, fix the two failing test cases and run *yarn run prettier*. 

```
packages/peregrine/lib/targets/__tests__/peregrine-targets.spec.js
packages/venia-ui/lib/targets/__tests__/venia-ui-targets.spec.js
```

Thank you in advance. Also, I recommend joining as Slack then we answer questions mutch faster

**https://devdocs.magento.com/community/resources.html**

2021-07-30 13:21 UTC, 0m3r commented
Can I fix test fails on "my" code?

something like below
```js
        const fs = require('fs');
...
        const context = path.resolve(__dirname, '../../../../../');
        const configPath = path.resolve(context, 'package.json');
        try {
            if (fs.existsSync(configPath)) {
                const config = require(configPath)['pwa-studio'];
                return config && config['trusted_vendors'] ? config['trusted_vendors'] : [];
                //file exists
            }
        } catch(err) {
          // console.error(err)
        }
        return [];
```

2021-07-31 18:03 UTC, larsroettig commented
Hi @jimbo. 
what do think about this PR like the idea and is very helpful for partners. 

kind regards.,

Lars

2021-08-03 17:03 UTC, larsroettig commented
One thinks about Extension `package.json` if some extension it allows itself via 
```
trusted_vendors":  [
      "@vendor"
   ]
```
Should be prevented in every case a `yarn install` should be *not* enough to get access to this low level to react extension point for security reasons.   

**Verification Steps**
* Checks for `trusted_vendors"` will only be parsed from the root  project `package.json`

2021-08-16 22:08 UTC, jimbo commented
> Hi @jimbo.
> what do think about this PR like the idea and is very helpful for partners.

I think it's great. We can certainly do more to expose components + API, as we do for talons, but this is a great way to relieve people's pain while we figure out those details.

2021-08-30 09:55 UTC, 0m3r commented on packages/pwa-buildpack/lib/WebpackTools/ModuleTransformConfig.js
> +        return config && config['trusted_vendors']
Fair enough

2021-08-30 10:42 UTC, 0m3r commented on packages/pwa-buildpack/lib/WebpackTools/ModuleTransformConfig.js
> +        const context = path.resolve(__dirname, '../../../../../');
to be honest, I found something similar in the code and used it.
process.cwd() like me more.

2021-08-30 10:46 UTC, 0m3r commented on packages/pwa-buildpack/lib/WebpackTools/ModuleTransformConfig.js
> +        const context = path.resolve(__dirname, '../../../../../');
https://github.com/magento/pwa-studio/pull/3266/commits/691cfdce9ccfd4b5399c55d3776bddf50fc7763d

2021-08-30 11:00 UTC, 0m3r commented
> @0m3r Add support for monorepo and I think @larsroettig was also requesting test coverage if possible. Otherwise this looks perfect, nice work

about tests

I did not find ModuleTransformConfig.spec.js
Unfortunately, I don't have enough experience to write this from scratch.

2021-09-01 19:56 UTC, tjwiebell commented
@0m3r Existing code appears to be tested by integration tests in other packages, there is no unit test. Instead of building all that out in this scope, I've created a manual test that we'll run during regression and aim to automate if it becomes a priority. Thank you for the contribution.

✅  QA Passed

2021-09-01 20:27 UTC, tjwiebell approved these changes

2021-09-01 20:28 UTC, merged