[Doc] Release notes 11.0.0
magento/pwa-studio pull request #3275
Opened 2021-07-15 19:50 UTC by jcalcaben

## Description

Update the changelog with release notes for the 11.0.0 release.

Also updates the compatibility table.

## Related Issue

Closes PWA-1875

## Acceptance

@davemacaulay 
@tkacheva 

### Verification Stakeholders

Any core developer

@davemacaulay 
@tkacheva 

### Specification

## Test Plan

1. Open CHANGELOG.md
2. Verify content is accurate
3. Open magento-compatibility.js
4. Verify content is accurate

#### Test scenario(s) for direct fix/feature
Example
-   Verify user is able to apply filters on category page
-   Verify user is able to apply filters on search page

#### Test scenario(s) for any existing impacted features/areas
Example
-   Verify user is able to sort data after applying filters on category page
-   Verify user is able to sort data after applying filters on search page

#### Test scenario(s) for any Magento Backend Supported Configurations
Example
- Update default Sort value in backend and repeat above scenarios

#### Is Browser/Device testing needed?
Example
- Yes, browser testing is needed as X UI component may be impacted on <browser>
- Yes, device testing is needed as X UI component may be impacted on <mobile|desktop|etc>

#### Any ad-hoc/edge case scenarios that need to be considered?
Example
- Apply all filters to get 0 results and then remove filters to see respective products 

## Screenshots / Screen Captures (if appropriate)

## Breaking Changes (if any)

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

2021-07-19 15:15 UTC, revanth0212 commented
Shouldn't this be against the release branch?

2021-07-19 15:40 UTC, davemacaulay requested changes
Overall looks great, a few minor updates :)

2021-07-19 15:40 UTC, davemacaulay commented on CHANGELOG.md
Could we add a link to where these tests live within the PWA Studio repository?

We would want our customers to be able to utilize these tests in their own CI/CD pipelines eventually, so might be worth adding a note around that.

2021-07-19 15:40 UTC, davemacaulay commented on CHANGELOG.md
I think we should make it clearer around the issues with the work we've done. The fact they cannot be purchased and will display a notice on the product page sounds like something helpful in these notes.

2021-07-19 15:40 UTC, davemacaulay commented on CHANGELOG.md
> +the `summaryPagePaymentTypes` target lets you add a custom payment summary in the checkout summary page.
Could we directly link both of these targets to their associated documentation?

2021-07-19 15:52 UTC, jcalcaben commented
@revanth0212 good catch! I changed the base to release/11.0

2021-07-21 15:09 UTC, davemacaulay approved these changes

2021-07-21 17:57 UTC, merged