PWA-1278: a11y mega menu
magento/pwa-studio pull request #3319
Opened 2021-08-05 10:39 UTC by pankhurigoel

## Description

TODO: Describe your changes in detail here.

## Related Issue

Closes #ISSUE_NUMBER.

## Acceptance

### Verification Stakeholders

### Specification

## Verification Steps

#### Test scenario(s) for direct fix/feature

#### Test scenario(s) for any existing impacted features/areas

#### Test scenario(s) for any Magento Backend Supported Configurations

#### Is Browser/Device testing needed?

#### Any ad-hoc/edge case scenarios that need to be considered?

## Screenshots / Screen Captures (if appropriate)

## Breaking Changes (if any)

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

2021-08-20 09:35 UTC, larsroettig requested changes
Please fix my comments and the falling test 

`packages/venia-ui/lib/components/MegaMenu/__tests__/MegaMenuItem.spec.js`

2021-08-20 09:35 UTC, larsroettig commented on packages/peregrine/lib/talons/MegaMenu/useSubMenu.js
> +        return false;
```suggestion
       return isFocused && subMenuState;
```

![Screenshot from 2021-08-20 11-28-11](https://user-images.githubusercontent.com/5289370/130212668-586a68c4-a0e4-4641-bfd0-5002ded07987.png)

2021-08-20 10:57 UTC, pankhurigoel commented on packages/peregrine/lib/talons/MegaMenu/useMegaMenu.js
> +    const useOutsideAlerter = ref => {
@supernova-at can you suggest a good name here

2021-08-20 14:29 UTC, revanth0212 submitted a review, later dismissed
I havent reviewed the whole PR but this seems odd to me. We shouldn't be defining talons inside of talons.

2021-08-20 14:29 UTC, revanth0212 commented on packages/peregrine/lib/talons/MegaMenu/useMegaMenu.js
> +    const useOutsideAlerter = ref => {
I am not sure if this is the right approach @pankhurigoel. We don't usually have talons inside of talons. You need to create a different file for it.

And for name, I think you are trying to handle blur on submenu. So maybe name it `useSubmenuBlurHandler`. I am open to opens for others on this.

2021-08-20 21:13 UTC, jimbo submitted a review, later dismissed

2021-08-20 21:13 UTC, jimbo commented on packages/peregrine/lib/talons/MegaMenu/useMegaMenu.js
> +    const useOutsideAlerter = ref => {
@revanth0212 is correct: returning a hook that the `MegaMenu` must call is not the correct approach. Instead, the `useMegaMenu` talon should perform the addition and removal of event listeners; if it needs a `navRef` to do so, it should get one from `props`.

```es6
// if this talon needs an external ref, get it from props
const { navRef } = props

// don't list refs in arrays of dependencies
const handleClickOutside = useCallback(event => {
    const { current: element } = navRef

    if (element && !element.contains(event.target)) {
        setDisableFocus(true)
        setSubMenuState(false)
    }
}, [setDisableFocus, setSubMenuState])

// import this utility hook from `peregrine/lib/hooks`
useEventListener(globalThis, "mousedown", handleClickOutside)
useEventListener(globalThis, "mouseout", handleClickOutside)
useEventListener(globalThis, "keydown", handleClickOutside)

// none of the above code needs to be returned from this talon
```

2021-09-02 00:42 UTC, tjwiebell requested changes
Some suggestions to be more consistent with the rest of the code base. This functions perfectly though, really nice work 👍

2021-09-02 00:42 UTC, tjwiebell commented on packages/peregrine/lib/talons/MegaMenu/useMegaMenuItem.js
> +        toggleSubMenu
Can we combine these two into a callback called `handleKeyDown`?

2021-09-02 00:42 UTC, tjwiebell commented on packages/peregrine/lib/talons/MegaMenu/useSubMenu.js
> +                e.target.addEventListener('blur', handleCloseSubMenu());
```suggestion
                e.target.addEventListener('blur', handleCloseSubMenu);
```

2021-09-02 00:42 UTC, tjwiebell commented on packages/venia-ui/lib/components/MegaMenu/megaMenuItem.js
> +                ) : null}
Consider extracting this to an element variable `moreChildrenIcon` or `downArrowIcon`. Some on the team like to indicate nullability by prefixing with `maybe<elementName>`, up to you just please extract.

2021-09-02 00:42 UTC, tjwiebell commented on packages/venia-ui/lib/components/MegaMenu/megaMenuItem.css
> +    padding-left: 8px;
Prefer rem units here
```suggestion
    padding-left: 0.5rem;
```

2021-09-02 00:42 UTC, tjwiebell commented on packages/venia-ui/lib/components/MegaMenu/megaMenuItem.js
> +                        size={17}
Any reason for the extra pixel? I would expect this to match the font-size of the menu item, which is defaulting to 1rem (16px).

2021-09-02 00:42 UTC, tjwiebell commented on packages/venia-ui/lib/components/MegaMenu/submenu.js
> +        }
```suggestion
            const keyboardProps = index === items.length - 1 ? talonProps.keyboardProps : {};
            return (
                <SubmenuColumn
                    index={index}
                    keyboardProps={keyboardProps}
                    key={category.id}
                    category={category}
                />
            );
```

2021-09-02 06:34 UTC, pankhurigoel commented on packages/peregrine/lib/talons/MegaMenu/useMegaMenu.js
> +            props.mainNavRef.current &&
Removing these lines is giving us errors as `handleClickOutside` function is called on mouse/keyboard events and the ref is attached to nav.

2021-09-02 18:04 UTC, tjwiebell requested changes
Really close, a few minor tweaks and we can send this to QA.

2021-09-02 18:04 UTC, tjwiebell commented on packages/venia-ui/lib/components/MegaMenu/megaMenuItem.js
> +                    handleKeyDown(e);
You shouldn't need to do your own binding here unless you're passing additional parameters. This can be:
`onKeyDown={handleKeyDown}`

2021-09-02 18:42 UTC, tjwiebell commented on packages/peregrine/lib/talons/MegaMenu/useMegaMenu.js
> +            props.mainNavRef.current &&
I figured this one out, and I'm not sure it was working as expected. You can remove these two lines but you need to fix `megaMenu.js` and make sure you're passing your props correctly. Should instead be `const talonProps = useMegaMenu({ mainNavRef });`.

2021-09-03 05:36 UTC, pankhurigoel commented on packages/peregrine/lib/talons/MegaMenu/useMegaMenuItem.js
> +    const handleKeyDown = e => {
We cannot do this because one function is preventing the default and if we just have one function then native `Tab` won’t work.

2021-09-03 19:21 UTC, tjwiebell approved these changes
All feedback has been addressed, just need an approval of my commit 08332ac before delivery. Sending to QA.

2021-09-03 19:22 UTC, tjwiebell commented on packages/venia-ui/lib/components/MegaMenu/megaMenuItem.js
> +                    handleKeyDown(e);
Fixed in 08332ac

2021-09-03 19:23 UTC, tjwiebell commented on packages/peregrine/lib/talons/MegaMenu/useMegaMenuItem.js
> +    const handleKeyDown = e => {
You can see how I merged these routines and simplified the logic a bit in 08332ac.

2021-09-06 13:06 UTC, larsroettig approved these changes

2021-09-07 15:16 UTC, merged