PWA-1850: Add to Cart on CMS - Out of stock is visible
magento/pwa-studio pull request #3433
Opened 2021-09-21 20:58 UTC by michaelyu0123

- Updated pagebuilder products to use url key instead of sku for getting products to fetch out of stock products

## Description
Closes: [[PWA-1850] Add to Cart on CMS - Out of stock is visible](https://jira.corp.magento.com/browse/PWA-1850)
Update template to properly show out of stock item in a CMS context.

## Related Issue

Closes #ISSUE_NUMBER.

## Acceptance

### Verification Stakeholders

### Specification

## Verification Steps

#### Test scenario(s) for direct fix/feature

#### Test scenario(s) for any existing impacted features/areas

#### Test scenario(s) for any Magento Backend Supported Configurations

#### Is Browser/Device testing needed?

#### Any ad-hoc/edge case scenarios that need to be considered?

## Screenshots / Screen Captures (if appropriate)

## Breaking Changes (if any)

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

2021-09-22 20:10 UTC, JustinConabreeAbsolunet requested changes
Very minor change request, and hopefully there's a way to use a less specific selector so it's less easy to break

2021-09-22 21:46 UTC, michaelyu0123 commented on packages/pagebuilder/lib/ContentTypes/Products/products.js
> +    const urlKeys = [...pathNames].map(pathName => {
updated

2021-09-23 13:43 UTC, JustinConabreeAbsolunet commented on packages/pagebuilder/lib/ContentTypes/Products/configAggregator.js
> +        '.product-item-details > .product-item-name > a.product-item-link'
Letting this one go since we need to ensure we only get one match per item.

2021-09-23 13:43 UTC, JustinConabreeAbsolunet approved these changes

2021-09-23 18:19 UTC, mikhaelbois commented
@michaelyu0123 
Product carrousel no longer showing on home page.
There are no errors in the console.
Those products are in stock and should not have been impacted by this PR.
I have also tested it on a local environment with the **Display Out of Stock Products** enabled and the products are not shown.
We only get an empty slide div.

2021-09-29 20:09 UTC, michaelyu0123 commented
> @michaelyu0123 Product carrousel no longer showing on home page. There are no errors in the console. Those products are in stock and should not have been impacted by this PR. I have also tested it on a local environment with the **Display Out of Stock Products** enabled and the products are not shown. We only get an empty slide div.

Resolved. It should show up now.

2021-09-30 12:45 UTC, JustinConabreeAbsolunet approved these changes
LGTM!

2021-09-30 13:51 UTC, mikhaelbois commented
@michaelyu0123 
Great, the slider is now showing again.
I'll do some testing on my local for the new features.

Also, coverage is slightly impacted. If it's not too much work, would it be possible to check that out?

2021-09-30 15:53 UTC, merged