[PWA-2235] Apollo cache eviction with multiple store view support
magento/pwa-studio pull request #3527
Opened 2021-10-28 16:50 UTC by mikhaelbois

## Description

[PWA-962](https://github.com/magento/pwa-studio/pull/3397) changed the cache clearing mechanism for sensitive data to use v3 Apollo's built in cache eviction. The problem is that this eviction will only clear for the current persistor. This regression was caught during the release process and since the previous mechanism was working correctly and the change didn't bring any new functionality, we reverted it for the release.

The goal of this task is to re-apply the v3 cache eviction, and find a workaround for clearing the inactive store view's persisted cache.

---

Refactoring cache clearing of customer and cart data to use Apollo v3's `evict` and garbage cleaning.

## Related Issue

Closes [PWA-2235](https://jira.corp.magento.com/browse/PWA-2235)

## Acceptance

- Utilities for manual cache deletion are deprecated - deleteCacheEntry
- These calls are replaced by cache.evict(), targeting specific entries that need purged
- After checking out, all references to cart are no longer present in InMemory or persisted cache in localStorage  **for all available stores**
- After logging out, all references to cart and customer data are no longer present in InMemory or persisted cache in localStorage **for all available stores**
- After creating an account, all references to cart and customer data are no longer present in InMemory or persisted cache in localStorage **in the other stores**
- After signing in, all references to cart and customer data are no longer present in InMemory or persisted cache in localStorage **in the other stores**
- Order History data should be removed from cache when signing out.

### Verification Stakeholders

## Verification Steps

#### Test scenario(s) for direct fix/feature

Test 1
- Sign-in as a customer
- Verify localStorage to see Apollo cache entries for customer data
- Add a new customer address (through checkout or through account)
- Add items to cart
- Verify cart data in localStorage
- Place order
- Entries for cart should be cleared (Cart will remain but with new ID)
- Sign out
- Entries for customer data should no longer be in cache

Test 2
- Sign-in as a customer
- Verify localStorage to see Apollo cache entries for customer data
- Add a new customer address (through checkout or through account)
- Add items to cart
- Verify cart data in localStorage
- Checkout a product, fill out all details on the checkout page but do not complete the order yet
- Switch to the `french` store
- Sign out
- Entries for cart and customer data should no longer be in cache

Test 3
- Navigate as guest
- Add items to cart
- Switch to the `french` store
- Verify cart data in localStorage in both stores
- Create a new account
- Entries for cart and customer data should no longer be in cache of the `default` store (They will be regenerated when you switch to that store)

Test 4
- Login
- Checkout an item and place an order on the default store
- Go to the order history page
- Validate in the Apollo caches that you have OrderItem data entries
- Switch to another store
- Logout
- Validate in the Apollo caches that you don't have OrderItem data entries remaining

## Breaking Changes (if any)

Removed `deleteCacheEntry` file/function

## Checklist

- [x] I have added tests to cover my changes, if necessary.
- [ ] ~I have added translations for new strings, if necessary.~
- [ ] ~I have updated the documentation accordingly, if necessary.~

2021-11-08 12:04 UTC, pankhurigoel reviewed
Looks good to me.

2021-11-12 20:02 UTC, tjwiebell requested changes
Looks good, have a couple suggestions for improvement before sending to QA.

2021-11-15 15:00 UTC, mikhaelbois commented on packages/peregrine/lib/talons/Adapter/__tests__/useAdapter.spec.js
> +                    },
@tjwiebell Done ✅

2021-11-15 15:00 UTC, mikhaelbois commented on packages/peregrine/lib/talons/Adapter/useAdapter.js
> +    const createCachePersistor = (storeCode, cache) => {
@tjwiebell Done ✅

2021-11-17 16:43 UTC, tjwiebell approved these changes

2021-11-18 17:54 UTC, dpatil-magento commented
QA Approved

2021-11-18 17:57 UTC, merged

2023-07-13 03:17 UTC, huykon commented
Hi @tjwiebell @mikhaelbois as I see after apply this PR, when we login at sign in or sign in popup header at cart page, some APIs (getItemCount, MiniCartQuery, ...) will error because it still call the old cartId
![image](https://github.com/magento/pwa-studio/assets/9253798/88f46040-a296-415f-9c62-ea743e25d3fd)