Venia Package > Adding devcontainer
magento/pwa-studio pull request #3556
Opened 2021-11-16 22:40 UTC by rafaelstz

It's going to add the devcontainer configuration to the project, making easier to start to work from local and remote environments, like Github Codespace.

2021-11-19 18:58 UTC, supernova-at commented
@magento create issue from PR

2021-11-22 21:08 UTC, jcalcaben requested changes
This is a neat addition! Could you create a short README file in the `.devcontainer` directory of this package that describes this feature and some of its limitations?

For example, local container development in vscode doesn't seem to support custom origins. Is it the same for Codespaces environments?

2021-11-23 15:45 UTC, jcalcaben commented on packages/venia-concept/.devcontainer/devcontainer.json
> +	"name": "PWA Studio",
```suggestion
	"name": "PWA Studio - Venia Template",
```

2021-12-06 21:19 UTC, jcalcaben commented
Closing this PR due to inactivity. Feel free to re-open and re-submit when you are able to address the feedback.

2021-12-06 21:19 UTC, closed without merging