Adding devcontainer
magento/pwa-studio pull request #3557
Opened 2021-11-16 22:51 UTC by rafaelstz

This PR adds a devcontainer to the root folder running specific commands to the main repo, it's going to speed up the development process to contributors start to code.

2021-11-19 18:58 UTC, supernova-at commented
@magento create issue from PR

2021-11-23 21:40 UTC, jcalcaben requested changes
As with #3556 this feature could use a README in the `.devcontainer` directory to describe the feature and limitations

2021-11-23 21:40 UTC, jcalcaben commented on .devcontainer/.env.sample
> +###############################################################################
isn't a file like this already being added in #3556 ? if so you can remove this file for this PR since it doesn't look like it's being used anywhere.

2021-12-06 21:19 UTC, jcalcaben commented
Closing this PR due to inactivity. Feel free to re-open and re-submit when you are able to address the feedback.

2021-12-06 21:19 UTC, closed without merging