[bugfix/3539] fixed issue #3539
magento/pwa-studio pull request #3578
Opened 2021-11-25 15:18 UTC by Jordaneisenburger

## Description

This fixes the related issue :)

## Related Issue

Closes #3539

## Acceptance

### Verification Stakeholders

@JustinConabreeAbsolunet 

### Specification

## Verification Steps

#### Test scenario(s) for direct fix/feature
Run the watcher notice that the <= tags get rendered as their actual value instead of the tag name.

#### Test scenario(s) for any existing impacted features/areas
no

#### Test scenario(s) for any Magento Backend Supported Configurations

#### Is Browser/Device testing needed?
no

#### Any ad-hoc/edge case scenarios that need to be considered?

## Screenshots / Screen Captures (if appropriate)

## Breaking Changes (if any)

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

2021-12-16 13:09 UTC, pedrochiossi requested changes
Code looks good, just need an extra line on .gitignore

2021-12-16 13:09 UTC, pedrochiossi commented on packages/venia-concept/.gitignore
> +template.generated.html
missing new line here

2021-12-21 14:31 UTC, pedrochiossi approved these changes

2021-12-21 21:30 UTC, ericeoeur commented
QA Passed, LGTM. Thanks!

2021-12-21 21:42 UTC, merged