[PWA-2063] Add reCaptcha to the Forgot Password Form
magento/pwa-studio pull request #3604
Opened 2021-12-08 15:42 UTC by mikhaelbois

## Description

Create hook that can be added to forms and enable the use of Google reCaptcha V3.
First form will be the Forgot Password Form.

## Related Issue

Closes https://jira.corp.magento.com/browse/PWA-2063.

## Acceptance

### Verification Stakeholders

### Specification

For this to work as needed, we need the following PR to be merged in our Magento PWA module.
This enables the config validation for the Request Forgot Password form.
PR:

## Verification Steps

#### Test scenario(s) for direct fix/feature

- Enable Google reCAPTCHA v3 Invisible in the admin.
- Set `Enable for Forgot Password` to v3 Invisible in the admin.
- In the frontend, test all occurrences of Forgot Password form (Mega menu, sidebar navigation, dedicated page and checkout).

#### Test scenario(s) for any existing impacted features/areas

- Test different configuration scenarios to make sure the Google API is not loaded if it is not assigned to the Forgot Password form or if it is disabled.
- Make sure other forms are not impacted.
- There should only one Google API script loaded and only when needed.

#### Is Browser/Device testing needed?

- Make sure API does not impact user experience on different browsers and on mobile / desktop.

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

2022-01-05 15:53 UTC, jcalcaben requested changes
just one minor comment. other than that, it looks good.

2022-01-05 16:15 UTC, mikhaelbois commented on packages/peregrine/lib/hooks/useScript.js
> + */
@jcalcaben Good point. Done!

2022-01-05 17:24 UTC, jcalcaben submitted a review, later dismissed

2022-01-06 22:01 UTC, dpatil-magento commented
@mikhaelbois Can get success response on graphql call and also see console error related security policy. We might need add google.com whitelist here https://github.com/magento/pwa-studio/blob/e488838019e6c77e6fd5f54f0a219699d8d4859d/packages/extensions/upward-security-headers/upward.yml#L22

![image](https://user-images.githubusercontent.com/40405790/148458328-3c8ee947-9dad-4fd1-bbe2-454ae4f83cb6.png)

2022-01-07 15:12 UTC, mikhaelbois commented
@magento give me 2.4.3 instance

2022-01-07 16:53 UTC, mikhaelbois commented
@dpatil-magento 
I've updated the CSP to include *.google frames.

2022-01-10 22:18 UTC, dpatil-magento commented
@mikhaelbois 
1. If I hit Cancel and go back to forgot password form don't see captcha again.

<a href="https://gyazo.com/3541322e2b527c8e87a4734fa9fb2168"><img src="https://i.gyazo.com/3541322e2b527c8e87a4734fa9fb2168.gif" alt="Image from Gyazo" width="482"/></a>

And if I try to submit email in above case, I get captcha failed error.

2. When configured to display Bottom right , The captcha does not go away until we reload page. I was expecting it to go away after we submit email or if I navigate to some new page using mega menu.

![image](https://user-images.githubusercontent.com/40405790/148847930-6a1384b1-f23c-4795-9c8e-fc1fc349b4a2.png)

2022-01-14 14:08 UTC, mikhaelbois commented
@dpatil-magento 
1. I'll resolve this issue.
2. Since the script is loaded once and stays active until we reload the page, I don't think we should or can hide the badge. Also, with the floating menu, it might become confusing to see the badge come and go every time the menu is toggled.

2022-01-24 21:58 UTC, ericeoeur approved these changes
LGTM. QA has passed for this ticket.

2022-01-24 22:05 UTC, merged