[PWA-2465] - Do not merge - Add Cypress test for About Us page
magento/pwa-studio pull request #3636
Opened 2022-01-07 18:07 UTC by jeremycharron

## Description

Cypress snapshot test for about us page

## Related Issue

Closes #PWA-2465

## Acceptance

### Verification Stakeholders

Project maintainers

### Specification

## Verification Steps

#### Test scenario(s) for direct fix/feature

1. Run test with yarn test:headless command and make sure it passes

#### Test scenario(s) for any existing impacted features/areas

N/A

#### Test scenario(s) for any Magento Backend Supported Configurations

N/A

#### Is Browser/Device testing needed?

No

#### Any ad-hoc/edge case scenarios that need to be considered?

No

## Screenshots / Screen Captures (if appropriate)

## Breaking Changes (if any)

No breaking change

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

2022-01-12 14:17 UTC, jeremycharron commented
Scaffold build is now successful.

2022-01-14 16:52 UTC, mikhaelbois requested changes
@jeremycharron 
Could we have the media files mocked as well?
You could use the mediaMockedCalls in the fixtures folder.

2022-01-14 16:54 UTC, jeremycharron commented
> You could use the mediaMockedCalls in the fixtures fold

Ok I'll take a look, thank you

2022-02-02 13:52 UTC, mikhaelbois approved these changes

2022-02-02 19:20 UTC, merged