AC-2478::Search results summary information not announced to screen r…
magento/pwa-studio pull request #3806
Opened 2022-04-27 11:00 UTC by glo82145

…eader users

## Description

TODO: Describe your changes in detail here.

## Related Issue

Closes #ISSUE_NUMBER.

## Acceptance

### Verification Stakeholders

### Specification

## Verification Steps

#### Test scenario(s) for direct fix/feature

#### Test scenario(s) for any existing impacted features/areas

#### Test scenario(s) for any Magento Backend Supported Configurations

#### Is Browser/Device testing needed?

#### Any ad-hoc/edge case scenarios that need to be considered?

## Screenshots / Screen Captures (if appropriate)

## Breaking Changes (if any)

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

2022-05-04 20:30 UTC, supernova-at commented
@magento create issue from PR

2022-05-11 16:07 UTC, michaelyu0123 requested changes

2022-05-20 10:17 UTC, glo82145 commented on packages/venia-ui/lib/components/SearchPage/searchPage.js
> +        data && !loading && data.products.items.length > 0 ? (
Hi @michaelyu0123 .. I have just added a condition  extra and no information has been removed from here. Could please explain more for better understanding

2022-05-24 13:43 UTC, supernova-at commented on packages/venia-ui/lib/components/SearchPage/searchPage.js
> +        data && !loading && data.products.items.length > 0 ? (
Hi @glo82145 , good question - take a look at the changes in the snapshot file above.

```
        <span
          className="totalPages"
        >
          0 items
        </span>
```

This `span` no longer gets rendered when there aren't any search results (`data.products.items.length = 0`). @michaelyu0123 is pointing out that we still do want to show the user the information in this case.

2022-05-24 15:29 UTC, michaelyu0123 requested changes

2022-05-31 07:37 UTC, nishant04412 commented on packages/venia-ui/lib/components/SearchPage/searchPage.js
> +        data && !loading && data.products.items.length > 0 ? (
@michaelyu0123 @supernova-at We have made the required changes. Now the behaviour is like '0 items' is showing on UX and screen reader is announcing 'No results found'. Please check and update if the code changes are acceptable.

2022-05-31 16:19 UTC, michaelyu0123 submitted a review, later dismissed

2022-05-31 18:29 UTC, dpatil-magento commented
run cypress

2022-06-01 05:13 UTC, dpatil-magento commented
run cypress @checkout

2022-06-01 05:27 UTC, dpatil-magento commented
run cypress @checkout

2022-06-01 06:14 UTC, dpatil-magento commented
run lighthouse-mobile

2022-06-01 06:15 UTC, dpatil-magento commented
run lighthouse-desktop

2022-06-01 06:31 UTC, dpatil-magento approved these changes
QA Approved.

2022-06-01 06:31 UTC, merged