PWA-2664: Swatches Components - Base Styles
magento/pwa-studio pull request #3852
Opened 2022-05-11 19:09 UTC by rwalter215

## Description

- Update Swatch & SwatchList style to reflect Base theme
- Update Tile & TileList style to reflect Base theme
- Update relevant unit tests/snapshots

## Related Issue

Closes [PWA-2664](https://jira.corp.magento.com/browse/PWA-2664).

## Acceptance
PM & UX Approval: Not approved yet

### Verification Stakeholders

### Specification

## Verification Steps

#### Test scenario(s) for direct fix/feature

#### Test scenario(s) for any existing impacted features/areas

#### Test scenario(s) for any Magento Backend Supported Configurations

#### Is Browser/Device testing needed?

#### Any ad-hoc/edge case scenarios that need to be considered?

## Screenshots / Screen Captures (if appropriate)

## Breaking Changes (if any)

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

2022-05-27 16:36 UTC, anthoula requested changes

2022-05-27 16:36 UTC, anthoula commented on packages/peregrine/lib/ui/components/ProductOptions/swatch.module.css
> +    composes: w-[2.5rem] from global;
Would the Tailwind basic usage work?

```
composes: h-10 from global;
composes: w-10 from global;
```

2022-05-31 13:21 UTC, anthoula commented on packages/peregrine/lib/ui/components/ProductOptions/swatch.module.css
> +    composes: w-[2.5rem] from global;
Can you check the PR for more instances that can use Tailwind's basic usage values? Thank you

2023-03-07 05:10 UTC, glo42707 commented
run cypress

2023-03-07 05:10 UTC, glo42707 commented
run lighthouse-mobile

2023-03-07 05:11 UTC, glo42707 commented
run lighthouse-desktop

2023-03-07 05:49 UTC, glo42707 commented
run pr-deploy

2023-08-10 14:44 UTC, glo42707 commented
run cypress

2024-05-29 11:15 UTC, closed without merging