AC-3522::Product search result with items count is not being read by …
magento/pwa-studio pull request #3882
Opened 2022-06-15 15:00 UTC by glo71317

…screen reader

## Description

TODO: Describe your changes in detail here.

## Related Issue

Closes #ISSUE_NUMBER.

## Acceptance

### Verification Stakeholders

### Specification

## Verification Steps

#### Test scenario(s) for direct fix/feature

#### Test scenario(s) for any existing impacted features/areas

#### Test scenario(s) for any Magento Backend Supported Configurations

#### Is Browser/Device testing needed?

#### Any ad-hoc/edge case scenarios that need to be considered?

## Screenshots / Screen Captures (if appropriate)

## Breaking Changes (if any)

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

2022-07-28 21:00 UTC, anthoula commented
@magento create issue from PR

2022-08-05 20:53 UTC, jcalcaben requested changes

2022-08-05 20:53 UTC, jcalcaben commented on packages/venia-ui/lib/components/SearchPage/searchPage.js
> +        productSortRoot.setAttribute('aria-hidden', 'true');
why is this set here and not directly in the `ProductSort` component?

2022-08-05 20:53 UTC, jcalcaben commented on packages/venia-ui/lib/components/SearchPage/searchPage.js
> +        filterSidebarRoot.setAttribute('aria-hidden', 'true');
why is this set here and not directly in the `FilterSidebar` component?

2022-08-05 20:53 UTC, jcalcaben commented on packages/venia-ui/lib/components/SearchPage/searchPage.js
> +            }, 15000);
this should be moved into the `ProductSort` component and done in a way such that a new timeout isn't scheduled everytime the component renders.

see: https://www.joshwcomeau.com/snippets/react-hooks/use-timeout/

2022-08-05 20:53 UTC, jcalcaben commented on packages/venia-ui/lib/components/SearchPage/searchPage.js
> +            }, 15000);
this should be moved into the `FilterSideBar` component and done in a way such that a new timeout isn't scheduled everytime the component renders.

see: https://www.joshwcomeau.com/snippets/react-hooks/use-timeout/

2022-08-30 09:59 UTC, glo71317 commented
As @glo82145 has created different pr for the fix

2022-08-30 09:59 UTC, closed without merging