Fix#AC-2494 No indication of required input fields (pattern: Required…
magento/pwa-studio pull request #3961
Opened 2022-09-21 07:19 UTC by RaghavendraTirumalasetti

… fields)

## Description

Reproduction Steps

Locations (representative sample):

Shopping Bag
Checkout - Shipping Information
Checkout - Payment
- Checkout - Confirmation / Create an Account
Sign In

1. Visually inspect form elements

Actual Behavior

There is no indication of which form fields are required. Examples include:

Module 05b - Shopping Bag
Module 06a - Checkout - Shipping Information
Module 06b - Checkout - Payment
Module 06c - Checkout - Confirmation / Create an Account
Module 07 - Sign In

Expected Behavior

Provide visual and programmatic instructions to indicate which fields are required.

## Related Issue

Closes https://jira.corp.adobe.com/browse/AC-2494

## Acceptance

### Verification Stakeholders

### Specification

## Verification Steps

#### Test scenario(s) for direct fix/feature

#### Test scenario(s) for any existing impacted features/areas

#### Test scenario(s) for any Magento Backend Supported Configurations

#### Is Browser/Device testing needed?

#### Any ad-hoc/edge case scenarios that need to be considered?

## Screenshots / Screen Captures (if appropriate)

## Breaking Changes (if any)

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

2022-10-28 15:20 UTC, anthoula commented
@magento create issue from PR

2022-11-14 21:10 UTC, anthoula requested changes
Thanks @RaghavendraTirumalasetti - Can you please add translations to all new strings?

2022-11-16 17:35 UTC, anthoula requested changes
Thanks @RaghavendraTirumalasetti ! Most of these can be global translation IDs.

2022-11-16 17:35 UTC, anthoula commented on packages/venia-ui/lib/components/CheckoutPage/OrderConfirmationPage/createAccount.js
> +                            id: 'Form.fistname',
```suggestion
                            id: 'global.firstNameRequired',
```

2022-11-16 17:35 UTC, anthoula commented on packages/venia-ui/lib/components/CheckoutPage/OrderConfirmationPage/createAccount.js
> +                            id: 'Form.lastname',
```suggestion
                            id: 'global.lastNameRequired',
```

2022-11-16 17:35 UTC, anthoula commented on packages/venia-ui/lib/components/CheckoutPage/OrderConfirmationPage/createAccount.js
> +                            id: 'Form.Email',
```suggestion
                            id: 'global.emailRequired',
```

2022-11-16 17:35 UTC, anthoula commented on packages/venia-ui/lib/components/CheckoutPage/OrderConfirmationPage/createAccount.js
> +                        id: 'Form.Password',
```suggestion
                        id: 'global.passwordRequired',
```

2022-11-16 17:35 UTC, anthoula commented on packages/venia-ui/lib/components/CheckoutPage/ShippingInformation/AddressForm/customerForm.js
> +                                id: 'Form.fistname',
```suggestion
                                id: 'global.firstNameRequired',
```

2022-11-16 17:35 UTC, anthoula commented on packages/venia-ui/lib/components/CheckoutPage/ShippingInformation/AddressForm/customerForm.js
> +                                id: 'Form.lastname',
```suggestion
                                id: 'global.lastNameRequired',
```

2022-11-16 17:35 UTC, anthoula commented on packages/venia-ui/lib/components/CheckoutPage/ShippingInformation/AddressForm/customerForm.js
> +                            id: 'Form.country',
```suggestion
                            id: 'global.countryRequired',
```

2022-11-16 17:35 UTC, anthoula commented on packages/venia-ui/lib/components/CheckoutPage/ShippingInformation/AddressForm/customerForm.js
> +                                id: 'Form.streetAddress',
```suggestion
                                id: 'global.streetAddressRequired',
```

2022-11-16 17:35 UTC, anthoula commented on packages/venia-ui/lib/components/CheckoutPage/ShippingInformation/AddressForm/customerForm.js
> +                            id: 'Form.country',
```suggestion
                            id: 'global.countryRequired',
```

2022-11-16 17:35 UTC, anthoula commented on packages/venia-ui/lib/components/CheckoutPage/ShippingInformation/AddressForm/customerForm.js
> +                                id: 'Form.city',
```suggestion
                                id: 'global.cityRequired',
```

2022-11-16 17:35 UTC, anthoula commented on packages/venia-ui/lib/components/CheckoutPage/ShippingInformation/AddressForm/customerForm.js
> +                            id: 'Form.state',
```suggestion
                            id: 'global.stateRequired',
```

2022-11-16 17:35 UTC, anthoula commented on packages/venia-ui/lib/components/CheckoutPage/ShippingInformation/AddressForm/customerForm.js
> +                            id: 'Form.postalCode',
```suggestion
                            id: 'global.postalCodeRequired',
```

2022-11-16 17:35 UTC, anthoula commented on packages/venia-ui/lib/components/CheckoutPage/ShippingInformation/AddressForm/customerForm.js
> +                                id: 'Form.phonenumber',
```suggestion
                                id: 'global.phoneNumberRequired',
```

2022-11-16 17:35 UTC, anthoula commented on packages/venia-ui/lib/components/CheckoutPage/ShippingInformation/AddressForm/guestForm.js
> +                                id: 'Form.Email',
```suggestion
                                id: 'global.emailRequired',
```

2022-11-16 17:35 UTC, anthoula commented on packages/venia-ui/lib/components/CheckoutPage/ShippingInformation/AddressForm/guestForm.js
> +                                id: 'Form.fistname',
```suggestion
                                id: 'global.firstNameRequired',
```

2022-11-16 17:35 UTC, anthoula commented on packages/venia-ui/lib/components/CheckoutPage/ShippingInformation/AddressForm/guestForm.js
> +                                id: 'Form.lastname',
```suggestion
                                id: 'global.lastNameRequired',
```

2022-11-16 17:35 UTC, anthoula commented on packages/venia-ui/lib/components/CheckoutPage/ShippingInformation/AddressForm/guestForm.js
> +                            id: 'Form.country',
```suggestion
                            id: 'global.countryRequired',
```

2022-11-16 17:35 UTC, anthoula commented on packages/venia-ui/lib/components/CheckoutPage/ShippingInformation/AddressForm/guestForm.js
> +                                id: 'Form.streetAddress',
```suggestion
                                id: 'global.streetAddressRequired',
```

2022-11-16 17:35 UTC, anthoula commented on packages/venia-ui/lib/components/CheckoutPage/ShippingInformation/AddressForm/guestForm.js
> +                                id: 'Form.city',
```suggestion
                                id: 'global.cityRequired',
```

2022-11-16 17:35 UTC, anthoula commented on packages/venia-ui/lib/components/CheckoutPage/ShippingInformation/AddressForm/guestForm.js
> +                            id: 'Form.state',
```suggestion
                            id: 'global.stateRequired',
```

2022-11-16 17:35 UTC, anthoula commented on packages/venia-ui/lib/components/CheckoutPage/ShippingInformation/AddressForm/guestForm.js
> +                            id: 'Form.postalCode',
```suggestion
                            id: 'global.postalCodeRequired',
```

2022-11-16 17:35 UTC, anthoula commented on packages/venia-ui/lib/components/CheckoutPage/ShippingInformation/AddressForm/guestForm.js
> +                                id: 'Form.phonenumber',
```suggestion
                                id: 'global.phoneNumberRequired',
```

2022-11-16 17:35 UTC, anthoula commented on packages/venia-ui/lib/components/CreateAccount/createAccount.js
> +                        id: 'Form.fistname',
```suggestion
                        id: 'global.firstNameRequired',
```

2022-11-16 17:35 UTC, anthoula commented on packages/venia-ui/lib/components/CreateAccount/createAccount.js
> +                        id: 'Form.lastname',
```suggestion
                        id: 'global.lastNameRequired',
```

2022-11-16 17:35 UTC, anthoula commented on packages/venia-ui/lib/components/CreateAccount/createAccount.js
> +                        id: 'Form.Email',
```suggestion
                        id: 'global.emailRequired',
```

2022-11-16 17:35 UTC, anthoula commented on packages/venia-ui/lib/components/CreateAccount/createAccount.js
> +                    id: 'Form.Password',
```suggestion
                    id: 'global.passwordRequired',
```

2022-11-16 17:35 UTC, anthoula commented on packages/venia-ui/lib/components/SignIn/signIn.js
> +                            id: 'Form.Email',
```suggestion
                            id: 'global.emailRequired',
```

2022-11-16 17:35 UTC, anthoula commented on packages/venia-ui/lib/components/SignIn/signIn.js
> +                        id: 'Form.Password',
```suggestion
                        id: 'global.passwordRequired',
```

2022-11-17 15:17 UTC, anthoula approved these changes

2022-11-17 21:25 UTC, dpatil-magento commented
run cypress

2022-11-18 00:35 UTC, merged