AC-2487::Accordions do not indicate current state
magento/pwa-studio pull request #3977
Opened 2022-10-12 11:16 UTC by glo82145

## Description

Accordions do not indicate current state.

Environment
Adobe Magento - Venia

Context
Windows 10; Chrome 88; JAWS 2021

Reproduction Steps
Locations (representative sample):

Search Results
Account - Order History
1. With JAWS operating, press Tab to move through the content.
2. When keyboard focus is on "Filter" button, press Enter or Space to activate it.
3. Within "Filter" menu tab to filters, press Enter or Space to activate accordion.

Actual Behavior
Accordions do not indicate current state information (expanded or collapsed). Examples include:

Module 03 - Search Results
Module 08 - Account - Order History

When controls do not provide state information, screen reader users will not know their current state.

Expected Behavior
For each control (accordions) that have multiple states (ie. expanded, collapsed), ensure the state is communicated to let the user know what will occur when they interact with the control. Use the aria-expanded attribute, set to true or false, to identify the current state.

## Related Issue

Closes [#AC-2487.](https://jira.corp.adobe.com/browse/AC-2487)

## Acceptance

### Verification Stakeholders

### Specification

## Verification Steps

#### Test scenario(s) for direct fix/feature

#### Test scenario(s) for any existing impacted features/areas

#### Test scenario(s) for any Magento Backend Supported Configurations

#### Is Browser/Device testing needed?

#### Any ad-hoc/edge case scenarios that need to be considered?

## Screenshots / Screen Captures (if appropriate)

## Breaking Changes (if any)

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

2022-10-28 15:13 UTC, anthoula commented
@magento create issue from PR

2022-11-10 16:37 UTC, anthoula requested changes
Thanks @glo82145 - Just some translations needed please

2022-11-10 16:37 UTC, anthoula commented on packages/venia-ui/lib/components/FilterModalOpenButton/filterModalOpenButton.js
> +            aria-label="Filter Button for Filter Options"
Can you add a translation for this string please?

2022-11-15 17:11 UTC, anthoula submitted a review, later dismissed

2022-11-15 19:52 UTC, dpatil-magento commented
run cypress

2022-11-15 20:59 UTC, dpatil-magento commented
lighthouse-desktop

2022-11-15 20:59 UTC, dpatil-magento commented
run lighthouse-mobile

2022-11-15 21:23 UTC, dpatil-magento commented
QA Approved.

2022-11-15 21:24 UTC, merged