AC-6679::The button is not usable by keyboard
magento/pwa-studio pull request #3980
Opened 2022-10-17 11:04 UTC by glo82145

## Description

TODO: <div class="table-wrap">

Environment | https://venia.magento.com/
-- | --
Testing Method | Observation
Resolution | Desktop
Page | Checkout
Location/Component | Place Order button
Issue description | The button is not usable by keyboard
Additional Note
Criteria Name | 2.1.1 Keyboard
Level | A
Impact | Blocker
Category | Visual, Motor, Cognitive
Responsibility | Developer
Fix (YES/NO) | Y
Fix Date |  

</div>

## Related Issue

Closes [#AC-6679.](https://jira.corp.adobe.com/browse/AC-6679)

## Acceptance

### Verification Stakeholders

### Specification

## Verification Steps

#### Test scenario(s) for direct fix/feature

#### Test scenario(s) for any existing impacted features/areas

#### Test scenario(s) for any Magento Backend Supported Configurations

#### Is Browser/Device testing needed?

#### Any ad-hoc/edge case scenarios that need to be considered?

## Screenshots / Screen Captures (if appropriate)

## Breaking Changes (if any)

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### Resolved issues:
1. [x] resolves magento/pwa-studio#3997: AC-6679::The button is not usable by keyboard

2022-10-28 20:46 UTC, anthoula commented
@magento create issue from PR

2022-11-14 15:47 UTC, jcalcaben requested changes

2022-11-14 15:47 UTC, jcalcaben commented on packages/peregrine/lib/talons/CheckoutPage/useCheckoutPage.js
> +            if (event.key === 'Enter') {
We should also add spacebar handling to this button as well

2022-11-15 20:19 UTC, jcalcaben approved these changes

2022-11-16 01:33 UTC, dpatil-magento commented
run cypress

2022-11-16 15:00 UTC, merged