Added release notes
magento/pwa-studio pull request #4015
Opened 2022-12-07 20:35 UTC by bdenham

## Description

Added first draft of release notes for v13.0.0. 

## Related Issue

Closes #[PWA-3036](https://jira.corp.adobe.com/browse/PWA-3036).

## Acceptance

Release notes are complete and accurate.

### Verification Stakeholders

- @dpatil-magento 
- @anthoula

2022-12-12 21:15 UTC, dpatil-magento commented on magento-compatibility.js
> +    '13.0.0': '2.4.6',
PWA 13.0  will support 2.4.5.

2022-12-12 21:18 UTC, dpatil-magento requested changes
Not sure why yarn.lock changed and committed. Please check, dont think its needed.

2022-12-13 20:45 UTC, anthoula requested changes

2022-12-13 20:45 UTC, anthoula commented on CHANGELOG.md
> +-  Story: [3980][] — Enabled keyboard navigation on on the Checkout page.
```suggestion
-  Story: [3980][] — Enabled keyboard navigation on the Checkout page.
```

2022-12-15 17:43 UTC, anthoula submitted a review, later dismissed

2023-01-05 23:08 UTC, dpatil-magento submitted a review, later dismissed

2023-01-06 05:49 UTC, dpatil-magento approved these changes

2023-01-06 21:53 UTC, merged