Added release notes
magento/pwa-studio pull request #4132
Opened 2023-06-15 08:01 UTC by glo82145

## Description

TODO: Describe your changes in detail here.

## Related Issue

Closes #ISSUE_NUMBER.

## Acceptance

### Verification Stakeholders

### Specification

## Verification Steps

#### Test scenario(s) for direct fix/feature

#### Test scenario(s) for any existing impacted features/areas

#### Test scenario(s) for any Magento Backend Supported Configurations

#### Is Browser/Device testing needed?

#### Any ad-hoc/edge case scenarios that need to be considered?

## Screenshots / Screen Captures (if appropriate)

## Breaking Changes (if any)

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

2023-06-15 13:18 UTC, supernova-at commented on CHANGELOG.md
> +The 13.0 release of PWA Studio provides customers with many accessibility improvements for keyboard and screen-reader access, as well as several bug fixes. Full details are described below.
```suggestion
The 13.2 release of PWA Studio ...
```

2023-06-15 13:18 UTC, supernova-at commented on CHANGELOG.md
> +The 13.0 release of PWA Studio provides customers with many accessibility improvements for keyboard and screen-reader access, as well as several bug fixes. Full details are described below.
Should say the `13.2.0` release of PWA Studio

2023-06-15 13:19 UTC, supernova-at requested changes
One minor fix but other than that it looks great!

2023-06-16 05:47 UTC, glo42707 submitted a review, later dismissed
approved

2023-06-19 13:46 UTC, supernova-at submitted a review, later dismissed

2023-06-20 09:37 UTC, glo82145 commented
run lighthouse-desktop

2023-06-20 09:37 UTC, glo82145 commented
run lighthouse-mobile

2023-06-20 10:45 UTC, glo42707 commented
run lighthouse-desktop

2023-06-20 12:41 UTC, glo42707 approved these changes
approving for develop PR Merge test

2023-06-20 12:46 UTC, glo42707 approved these changes
approving again for release/13.2 branch test if able to merge

2023-06-20 13:02 UTC, merged